name: Bun CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Lint, Format, Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/bun@v1
        with:
          version: '1.2.20'

      - name: Install dependencies
        run: bun install

      - name: Run ESLint
        run: bun run lint

      - name: Run Prettier check
        run: bun run format -- --check

      - name: Run Turbo build
        run: bun run build

      - name: Check Types
        run: bun run check-types